# Generated by Django 5.0.7 on 2024-07-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the customer', max_length=100)),
                ('address', models.CharField(help_text='Address of the customer', max_length=200)),
                ('phone', models.CharField(help_text='Phone number of the customer', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address of the customer', max_length=254, null=True)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('government', 'Government'), ('organization', 'Organization'), ('other', 'Other')], default='individual', help_text='Type of the customer', max_length=20)),
                ('district', models.CharField(help_text='District of the customer', max_length=100)),
                ('subdistrict', models.CharField(help_text='Subdistrict of the customer', max_length=100)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
