# Generated by Django 5.0.7 on 2024-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address_alter_customer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate'), ('Business', 'Business'), ('Government', 'Government'), ('Organization', 'Organization'), ('Other', 'Other')], default='individual', max_length=20),
        ),
    ]
